---
name: checklist workflow
on:
  push:
    branches: ['testing']
jobs:
  checklist:
    runs-on: ubuntu-latest
    environment: 'manual_approval'
    name: Check env and settings
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check env
        run: |
          make -s check_env
      - name: Check settings
        run: |
          make -s check_settings
  runlist:
    runs-on: ubuntu-latest
    needs: 'checklist'
    name: Get deployment env
    steps:
      - name: Step 1
        run: |
          cat ${{ github.env }}
          cat ${{ github.vars }}