---
name: Run a basic openQA test
on:
  pull_request_target:
  workflow_dispatch:
jobs:
  manual_approval_wait:
    runs-on: ubuntu-latest
    environment: manual_approval
    steps:
      - name: manual approval check
        run: |
          echo 'Manual approval OK'
  trigger_and_monitor_openqa:
    runs-on: ubuntu-latest
    needs: manual_approval_wait
    steps:
      - uses: actions/checkout@v3
      - name: openQA init
        id: latest_build
        run: |
          make -s openQA_init
      - name: openQA trigger
        run: |
          make -s openQA_trigger
  clone_mentioned_job:
    runs-on: ubuntu-latest
    needs: manual_approval_wait
    steps:
      - name: Clone and monitor job mentioned in PR description
        run: |
          make -s hello
