---
name: Run a basic openQA test
on:
  pull_request_target:
  workflow_dispatch:
jobs:
  compile_test:
    runs-on: ubuntu-latest
    steps:
      - uses: ./github/workflows/ci_workflow_call.yml
  trigger_and_monitor_openqa:
    runs-on: ubuntu-latest
    needs: compile_test
    environment: 'manual_approval'
    steps:
      - uses: actions/checkout@v3
      - name: openQA init
        id: latest_build
        run: |
          make -s openQA_init
      - name: openQA trigger
        run: |
          make -s openQA_trigger
  clone_mentioned_job:
    runs-on: ubuntu-latest
    needs: compile_test
    environment: 'manual_approval'
    steps:
      - name: Clone and monitor job mentioned in PR description
        run: |
          make -s hello
